// FAIL: data_pekerja.js
const senaraiPekerja = {
    // ==========================================
    // AKAUN PENGURUSAN (MANAGER / ENGINEER)
    // ==========================================
    "ENG01": { pass: "admin123", role: "manager", nama: "Bos Salik" },
    "MGR99": { pass: "bosbesar", role: "manager", nama: "Pengurus Besar" },

    // ==========================================
    // AKAUN OPERATOR KILANG (DARI SENARAI SEBENAR)
    // ==========================================
    "1549": { pass: "1549", role: "operator", nama: "MUHD SALIHIN" },
    "1938": { pass: "1938", role: "operator", nama: "MAHARA RAJ KUMAR" },
    "1904": { pass: "1904", role: "operator", nama: "MIAH MD SABUJ" },
    "1944": { pass: "1944", role: "operator", nama: "THAKU RAM KUMAR CHAUDARY" },
    "1901": { pass: "1901", role: "operator", nama: "ISLAM JAHER" },
    "1965": { pass: "1965", role: "operator", nama: "MD JAMAL HOSSAIN" },
    "1839": { pass: "1839", role: "operator", nama: "MAHBUB ALAM" },
    "1674": { pass: "1674", role: "operator", nama: "THING ISHOR" },
    "1840": { pass: "1840", role: "operator", nama: "NAZMUL ALAM" },
    "1942": { pass: "1942", role: "operator", nama: "SHRESTHA RABIN" },
    "1585": { pass: "1585", role: "operator", nama: "MUHAMMAD AZAM" },
    "1851": { pass: "1851", role: "operator", nama: "RUBEL" },
    "1732": { pass: "1732", role: "operator", nama: "MOHD ADNAN" },
    "1870": { pass: "1870", role: "operator", nama: "MIAH MD MITON" },
    "1937": { pass: "1937", role: "operator", nama: "MAHARA NAGENDRA" },
    "1934": { pass: "1934", role: "operator", nama: "CHAUDUARY DURGESH" },
    "1680": { pass: "1680", role: "operator", nama: "RAJ KISHOR RAY" },
    "1524": { pass: "1524", role: "operator", nama: "HLA PYAE AUNG" },
    "2013": { pass: "2013", role: "operator", nama: "PYAE PHYO OO" },
    "1969": { pass: "1969", role: "operator", nama: "MD IMON" },
    "1973": { pass: "1973", role: "operator", nama: "MD BAHARUL MOLLA" },
    "1970": { pass: "1970", role: "operator", nama: "A SAMAD" },
    "1972": { pass: "1972", role: "operator", nama: "MD ZIAOUL HOQ" },
    "1981": { pass: "1981", role: "operator", nama: "FARID MD" },
    "1985": { pass: "1985", role: "operator", nama: "SHAHIDULLAH MD" },
    "2020": { pass: "2020", role: "operator", nama: "AYE NYEIN AUNG" },
    "1864": { pass: "1864", role: "operator", nama: "HASSAN MD ABIR" },
    "1857": { pass: "1857", role: "operator", nama: "HOSSAIN MANIK" },
    "1838": { pass: "1838", role: "operator", nama: "RIMON MIAH" },
    "1971": { pass: "1971", role: "operator", nama: "MD HABIB ULLAH" },
    "1968": { pass: "1968", role: "operator", nama: "JAMAL BISWAS" },
    "1974": { pass: "1974", role: "operator", nama: "MD GAHER ALI" },
    "1977": { pass: "1977", role: "operator", nama: "ANOWAR HOSSAIN" },
    "1983": { pass: "1983", role: "operator", nama: "MIA MD SHAKIL" },
    "1984": { pass: "1984", role: "operator", nama: "SAGOR ABU JABAR MIA" },
    "1982": { pass: "1982", role: "operator", nama: "HOSSAIN SABBIR" },
    "2025": { pass: "2025", role: "operator", nama: "THEIN THAN OO" },
    "2021": { pass: "2021", role: "operator", nama: "HEIN PYYO AUNG" },
    "2027": { pass: "2027", role: "operator", nama: "YE MIN AUNG" },
    "2023": { pass: "2023", role: "operator", nama: "KYAW THAT OO" },
    "2059": { pass: "2059", role: "operator", nama: "MUHAMMAD SYAFIQ" },
    "2069": { pass: "2069", role: "operator", nama: "MUHAMMAD DANIAL HAIKAL" },
    "2091": { pass: "2091", role: "operator", nama: "WAIBA NABIN" },
    "2092": { pass: "2092", role: "operator", nama: "MUKTAN TEK BAHADUR" },
    "2093": { pass: "2093", role: "operator", nama: "RAY RAMOD" },
    "2097": { pass: "2097", role: "operator", nama: "KHADKA DAMBAR BAHADUR" },
    "2098": { pass: "2098", role: "operator", nama: "AIMAN SYAFIQ" },
    "2099": { pass: "2099", role: "operator", nama: "WAIBA AKAL BAHADUR" },
    "2103": { pass: "2103", role: "operator", nama: "SHYAM KARKI" },
    };